apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebserver-deployment-name
spec: # Estado deseado
  replicas: 2
  selector:
    matchLabels:
      app: gowebserver_MATCH_LABELS
  template: # Aca definimos el POD
    metadata:
      labels:
        app: gowebserver_MATCH_LABELS
    spec:
      containers:
      - name: gowebserver-container
        image: maxizapata/gowebserver-arm64
        ports:
        - name: webserver-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: webserver-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: webserver-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
#      nodeSelector:
#        kubernetes.io/hostname: r4-worker1
